/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6202a6d5-9e08-4f5d-a84d-09c46c9838f0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qZU7zokVP",
    "aws_user_pools_web_client_id": "6c2gtgqu0ng2e4p5afobcb77e",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://k7zkd5vcifcfrc75jjqhbunjli.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-opojh4dtifcvfmcuojhzrwmk2y"
};


export default awsmobile;
