/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_user_files_s3_bucket": "kirastoragebucket112236-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://k7zkd5vcifcfrc75jjqhbunjli.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-opojh4dtifcvfmcuojhzrwmk2y"
};


export default awsmobile;
